[package]
name = "factories"
version = "0.1.0"
edition = "2021"

[dependencies]
serialisers = { path = "../serialisers" }
shared = { path = "../shared" }
models = { path = "../models" }
diesel = { version = "2.2.0", features = ["postgres"] }
